### ISSUE TITLE
bug(commands): multiple tags

### ISSUE THREAD

**Issue by HoJunHao2000** [AY2223S1-CS2103T-W10-4/tp#104]
Not sure if this will be fixed using JCommander but I realised if you have multiple inputs

e.g. add -m -c ST2334 -c MA1521

the command will still execute taking the 2nd tag

so MA1521 will be added and ST2334 would not be added

this applies to other tagged commands too

**Comment by domoberzin** [comment]
Could discuss having this as a functionality actually. Rationale being that when a user is onboarding and launching the app for the first time, they could add everything in a single command. Not sure what kind of bugs this may introduce though

**Comment by jontmy** [comment]
JCommander catches duplicate flags and throws a `ParameterException`, which I have modified `ModtrektParser` to catch and rethrow as a `ParseException` such that the error message is shown in the UI.

<img width="783" alt="Screenshot 2022-10-21 at 09 34 09" src="https://user-images.githubusercontent.com/50949210/197090571-9232c8aa-5403-4f1e-967a-424cca35766a.png">

If you want to support multiple inputs, the way to do it is by `@Parameter(arity = <number of inputs>)` on a `List<T>` field (and `IStringConverter<List<T>>` if necessary).

See:
[https://jcommander.org/#_lists](https://jcommander.org/#_lists)
[https://jcommander.org/#_fixed_arities](https://jcommander.org/#_fixed_arities)

**Comment by jontmy** [comment]
Closing as we're converting all commands to use JCommander.
