### ISSUE TITLE
[PE-D][Tester D] Add module command bug

### ISSUE THREAD

**Issue by nus-se-script** [AY2223S1-CS2103T-W10-4/tp#167]
![image.png](https://raw.githubusercontent.com/weiquany/ped/main/files/91f326ae-a810-4ee2-a863-ae08a058f20b.png)

Unable to add module manually, if there is a whitespace. There is also a discrepancy in the UG for the add module command and the actual command requirements.

Update: Using double quotes will solve this problem, but it was not stated anywhere and have to be inferred.

-------------
Labels: `type.FunctionalityBug` `severity.Low`
original: weiquany/ped#1

**Comment by jontmy** [comment]
Merging into #199.

Requirement for quotes is documented in UG - General Command Syntax.
