### ISSUE TITLE
[PE-D][Tester A] Unable to add module manually

### ISSUE THREAD

**Issue by nus-se-script** [AY2223S1-CS2103T-W10-4/tp#178]
Got an error message when trying to add a module.

It says that there was an error fetching data from NUSmods and suggested manually adding the module.

However, there was no advice given on how to add the module manually and I am unable to continue.

![Screenshot (39).png](https://raw.githubusercontent.com/Edfernape/ped/main/files/39beb438-8f95-4b17-a854-fe641065a1be.png)

-------------
Labels: `type.FeatureFlaw` `severity.Medium`
original: Edfernape/ped#2

**Comment by domoberzin** [comment]
I am unsure how the user managed to get that error utilising the `cs2103` mod code since it is present in the backup files and on NUSMods, but regardless I have added more descriptive error messages to show the verbose syntax to the user.
