### ISSUE TITLE
[PE-D][Tester C] Duplicated tasks allowed

### ISSUE THREAD

**Issue by nus-se-script** [AY2223S1-CS2103T-W10-4/tp#196]
It would be nice if you can prevent users from adding the duplicating tasks although it is not mentioned as a function in UG.

![image.png](https://raw.githubusercontent.com/ngquyduc/ped/main/files/d3c9ec45-78fc-494f-8672-f6bcf663857b.png)

-------------
Labels: `type.FunctionalityBug` `severity.Low`
original: ngquyduc/ped#9

**Comment by jontmy** [comment]
Closing as this is a suggestion and cannot be implemented during the feature freeze of 1.4.
