### ISSUE TITLE
rfc(deadline): restricting deadlines to future dates only

### ISSUE THREAD

**Issue by jontmy** [AY2223S1-CS2103T-W10-4/tp#203]
Quoting #201:

> Also worth considering - should we restrict dates to >= current year? Not sure if it may be considered a bug that we can set deadlines to be year 100, for example.

**Comment by vvidday** [comment]
Also not sure if we can even add this (is the extra check considered a feature?)

**Comment by midnightfeverrr** [comment]
@vvidday Adding an edge case should not count as a feature.
