### ISSUE TITLE
docs: update UG or implement its specifications

### ISSUE THREAD

**Issue by vvidday** [AY2223S1-CS2103T-W10-4/tp#72]
Currently our UG differs from the implementation (e.g. we're using the full command words like `remove` with 'shorthand' prefixes like `-m`, instead of `remove module` or `rm -m` like in the UG)

We should discuss & decide how we want to approach this (stick to current implementation & update UG, or update code to comply with UG)

**Comment by jontmy** [comment]
Closing as resolved - update UG in 1.3.2 and 1.4.
