### ISSUE TITLE
rfc: external library for command parsing

### ISSUE THREAD

**Issue by jontmy** [AY2223S1-CS2103T-W10-4/tp#75]
## Introduction

`ArgumentTokenizer` is poorly implemented and using `ArgumentMultimap` results in `Optional` _and_ `try/catch` hell, especially when considering optional flags.

`ArgumentTokenizer` also does not support positional arguments, which means otherwise trivial commands such as that to add a task requires redundant prefixes in `add -m -c <module code> -n <name> -cr <mcs>`.

I created `CommandParser` in #62 to standardize validation for required arguments, but adding support for aliasing (see #72) as well as the positional arguments would need a full parser implementation, i.e. non-trivial.

## Proposal

I propose that we request for [JCommander](https://jcommander.org/#_overview) in the CS2103T forum and ditch the stopgap `CommandParser` and `ArgumentTokenizer` altogether.

Alternatively, [Apache Commons CLI](https://commons.apache.org/proper/commons-cli/usage.html) has already been approved ([here](https://github.com/nus-cs2103-AY2223S1/forum/issues/319#issue-1392216603)), but JCommander has a more modern interface with annotations and built-in validation (!!).

Thoughts?

**Comment by vvidday** [comment]
Let's discuss this after tutorial today

**Comment by jontmy** [comment]
Requested in CS2103T forum as decided.

**Comment by jontmy** [comment]
Closed as approved.
