### ISSUE TITLE
bug(tasks): archive tasks not updating tasklist in module

### ISSUE THREAD

**Issue by vvidday** [AY2223S1-CS2103T-W10-4/tp#77]
Steps to reproduce:
1) Add a task
2) Archive it
3) Remove it
4) Task still counted in module tag & exists in `modulelist.json`

Reason: `isArchived` property of tasks in `Module`'s `taskList` isn't updated in `ArchiveTaskCommand::execute()` and `UnarchiveTaskCommand::execute()` so they don't pass the `.equals()` check during deletion and don't get deleted

Part of the problem with our current setup with two "sources of truth"

**Comment by jontmy** [comment]
I think the modules should just filter the entire task list based on whether the task has the same module code. Archiving is implemented in the same way.

This is less efficient (requiring a linear scan) but is simpler to implement and eliminates the errant source of truth from storing tasks in modules.

**Comment by vvidday** [comment]
Sounds good, `cd` also does a linear scan. Will work on this when I get the time

**Comment by HoJunHao2000** [comment]
> Sounds good, `cd` also does a linear scan. Will work on this when I get the time

I can work on it now

**Comment by vvidday** [comment]
> > Sounds good, `cd` also does a linear scan. Will work on this when I get the time
> 
> I can work on it now

Cool thanks!
